[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_CARGO_PROFILE = "release"
DEFAULT_PROFILE_FLAG = "--release"
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = "cli"

[tasks.full-build-cli]
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = "cli" }
run_task = { name = [
    "build-win64",
    "build-win-arm64",
    "build-linux64-gnu",
    "build-linux-arm64-gnu",
    "build-linux64-musl",
    "build-linux-arm64-musl"
], fork = true }

[tasks.build-win64]
command = "cross"
args = ["build", "--target", "x86_64-pc-windows-msvc", "${DEFAULT_PROFILE_FLAG}"]

[tasks.build-win-arm64]
command = "cross"
args = ["build", "--target", "aarch64-pc-windows-msvc", "${DEFAULT_PROFILE_FLAG}"]

[tasks.build-linux64-gnu]
command = "cross"
args = ["build", "--target", "x86_64-unknown-linux-gnu", "${DEFAULT_PROFILE_FLAG}"]

[tasks.build-linux-arm64-gnu]
command = "cross"
args = ["build", "--target", "aarch64-unknown-linux-gnu", "${DEFAULT_PROFILE_FLAG}"]

[tasks.build-linux64-musl]
command = "cross"
args = ["build", "--target", "x86_64-unknown-linux-musl", "${DEFAULT_PROFILE_FLAG}"]

[tasks.build-linux-arm64-musl]
command = "cross"
args = ["build", "--target", "aarch64-unknown-linux-musl", "${DEFAULT_PROFILE_FLAG}"]